-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#3a4c4e'
local Color4 = '#8fd8db'
local Color5 = '#141D22'
local Color7 = '#161f25'
local Color8 = '#141d22'
local Color2 = '#3f9bbc'
local Color3 = '#4DDCFF'
local Color1 = '#3df2ad'
local Color6 = '#A5FBFF'

highlight('Comment', nil, Color0, nil)
highlight('Constant', nil, Color1, nil)
highlight('String', nil, Color2, nil)
highlight('Number', nil, Color3, nil)
highlight('StatusLine', Color4, Color5, nil)
highlight('WildMenu', Color5, Color6, nil)
highlight('Pmenu', Color5, Color6, nil)
highlight('PmenuSel', Color6, Color7, nil)
highlight('PmenuThumb', Color5, Color6, nil)
highlight('Normal', Color5, Color6, nil)
highlight('SignColumn', Color5, nil, nil)
highlight('LineNr', nil, Color0, nil)
highlight('TabLine', Color8, nil, nil)
highlight('TabLineSel', Color6, Color7, nil)
highlight('TabLineFill', Color8, nil, nil)
highlight('TSPunctDelimiter', nil, Color6, nil)

link('TSTagDelimiter', 'Type')
link('TSFuncMacro', 'Macro')
link('TSType', 'Type')
link('TSParameter', 'Constant')
link('TSConditional', 'Conditional')
link('Folded', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSLabel', 'Type')
link('TSOperator', 'Operator')
link('TSString', 'String')
link('TSField', 'Constant')
link('NonText', 'Comment')
link('TSProperty', 'TSField')
link('TSNumber', 'Number')
link('Macro', 'Function')
link('TSFloat', 'Number')
link('TSTag', 'MyTag')
link('TSKeyword', 'Keyword')
link('TSComment', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSConstant', 'Constant')
link('TSRepeat', 'Repeat')
link('TSNamespace', 'TSType')
link('Repeat', 'Conditional')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('CursorLineNr', 'Identifier')
link('Conditional', 'Operator')
link('Operator', 'Keyword')
link('Whitespace', 'Comment')
